# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Milena Pribić
email: hello@milena.io
description: > # this means to ignore newlines until "baseurl:"
  I'm Milena, a Product Designer with IBM Design in Austin, Texas. I'm focused on dynamic, user-friendly designs. I like to draw, read, and go to rap shows.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: milenapribic
github_username:  milenapribic

permalink: /:title

# Build settings
markdown: kramdown
